import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Colorize } from "@/common/Style/color";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import Aside from "@/components/aside/Aside";
import HiddenHeader from "@/components/header/HiddenHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotify-TeamProject",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="sm:flex"
        style={{ backgroundColor: Colorize.Secondary_02 }}
      >
        <div className=" sm:flex-1/6 justify-center">
          <Aside />
        </div>
        <div className="sm:flex-5/6 ">
          <Header />
          <HiddenHeader />
          <div>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
