import type { Metadata } from "next";
import "./globals.css";
import { Colorize } from "@/common/Style/color";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Aside from "@/components/layout/Aside";

export const metadata: Metadata = {
  title: "Spotify-TeamProject",
  description: "Generated by create next app",
  icons: "./metaicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="sm:flex"
        style={{ backgroundColor: Colorize.Secondary_02 }}
      >
        <div className=" sm:flex-1/6 justify-center">
          <Aside />
        </div>
        <div className="sm:flex-5/6 ">
          <Header />
          <div>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
